# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/CYN"

# ç½‘é¡µçš„æ ‡é¢˜
title: "ä¸€åªå°çŒªå’ª"
subTitle: ""å“‡ï¼ï¼ï¼å¤§ç¾å¥³ï¼ï¼ï¼ğŸ§"
# ç½‘ç«™å‰¯æ ‡é¢˜

description: "å“‡ï¼ï¼ï¼å¤§ç¾å¥³ï¼ï¼ï¼ğŸ§"
aboutme: "âš ï¸æ³¨æ„"


# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
